// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kiaadksbsintnmgqgyzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpYWFka3Nic2ludG5tZ3FneXp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NTI2ODQsImV4cCI6MjA2NjMyODY4NH0.bs23eLzHKzd6bubq6JxKm95UeZnBUgGrD4fBmVDJfKg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);